- name: install pre-req packages
  apt:
    name: 
      - apt-transport-https
      - gpg-agent
      - gnupg
    state: present
    update_cache: yes

- name: Add an Apt signing key for erlang
  apt_key:
    url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc
    state: present


- name: Add erl repo 
  apt_repository:
    repo: "{{ erl_baseurl_debian }}"
    state: present
    filename: bintray.erlang.list
    update_cache: no

- name: install erl 
  apt:
    name: erlang
    state: present
    update_cache: yes
